# Spring配置
spring:
  # 数据库配置
  datasource:
    druid:
      webStatFilter.enabled: false
      statViewServlet.enabled: false
      filter.stat.enabled: false
      # 主库数据源
      master:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ry-vue}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  # redis 配置
  redis:
    # 地址
    host: ${REDIS_HOST:localhost}
    # 端口，默认为6379
    port: ${REDIS_PORT:6379}
    # 数据库索引
    database: 0
    # 密码
    password:

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: 待补充
  # 令牌有效期（默认30分钟）
  expireTime: 30
  refreshExpireTime: 10080

# Swagger配置，生产环境关闭
swagger:
  # 是否开启swagger
  enabled: false

springfox:
  documentation:
    # 总开关（同时设置auto-startup=false，否则/v3/api-docs等接口仍能继续访问）
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false
